config/routes.rb
Seekeapp::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :users, :only => [:show]
  resources :user_steps

  get 'about' => 'pages#about'

  root :to => 'pages#home'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

	def about
	end

end

app/controllers/user_steps_controller.rb
class UserStepsController < ApplicationController
  include Wicked::Wizard
  steps :personal, :social
  
  def show
    @user = current_user
    render_wizard
  
 end

        def update
    @user = current_user
    case step
    when :personal
            @user.update_attributes(params[:user])
    end
    sign_in(@user, :bypass => true)
    render_wizard @user
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    user_steps_path
  end
end

app/helpers/after_registration_helper.rb
module AfterRegistrationHelper
end

app/helpers/after_signup_helper.rb
module AfterSignupHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/user_steps_helper.rb
module UserStepsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
 <small>
		<a href="http://seeke.co">Seeke</a>
		by Hannah Wasserman
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <a class="brand" href="/">Seeke</a>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li>
                            <%= link_to 'Home',  root_path %>
                        </li>
                        <li>    
                            <%= link_to 'About',  about_path %>
                        </li>
                    </ul>
                <ul class="nav pull-right">
                        <% if user_signed_in? %>
                            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                        <% else %>
                            <li><%= link_to 'Login', new_user_session_path %></li>
                            <% end %>
                    </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seekeapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
       <% end %>
    
    <%= yield %>

    <%= render 'layouts/footer' %>
</div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/home.html.erb
<div class="center hero-unit">
	

<h1>Welcome to Seeke</h1>
<p>
	Planning your best weekends ever
</p>

<p> <%= link_to 'Sign up now!', new_user_registration_path , class: "btn btn-large btn-primary" %> </p>

</div>

<div class="row">
  <div class="span4">
	
	<img src="http://thesugarmagnolia.files.wordpress.com/2013/07/downthisroad-09.jpg?w=200&h=200" class="img-polaroid">
	
	<h2>Never be Bored</h2>
		<p>Seeke gives you a custom itinerary for your weekend. Whether your hanging in your neighborhood or visiting a new city, you will never have to ask, "What are we doing this weekend" again.</p>
  </div>
  
  <div class="span4">

<img src="http://thesugarmagnolia.files.wordpress.com/2012/07/amandapeetshouse1.jpeg?w=250&h=210" class="img-polaroid">

<h2>Just for You</h2>
  <p>We plan out your weekends based on your personality, interests and what going on around you. If you don't a component of your plan, no worries, just switch it out for something new.</p>
  </div>
 
 <div class="span4">

<img src="http://thesugarmagnolia.files.wordpress.com/2013/08/cote-de-azure-by-irene-suchocki.jpg?w=200&h=200" class="img-polaroid">

 <h2>It's Taken Care of</h2>
 <p>From making reservations to mapping your directions to your next destination, we've got you covered. All you have to do is follow the plan and have fun!</p>
 </div>
</div>

app/views/user_steps/_form.html.erb
<%= form_for @user, url: wizard_path do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= yield f %>
  
  <div class="actions">
    <%= f.submit "Continue" %>
    or <%= link_to "skip this step", next_wizard_path %>
  </div>
<% end %>

app/views/user_steps/personal.html.erb
<h1>Tell us a little about yourself.</h1>

<%= render layout: 'form' do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
<% end %>

app/views/user_steps/social.html.erb
<h1>Where can we find you.</h1>

<%= render layout: 'form' do |f| %>
  <h5> How old are you?</h5>
  <%= radio_button_tag(:age, "child") %>
<%= label_tag(:age_child, "I am younger than 21") %>
<%= radio_button_tag(:age, "adult") %>
<%= label_tag(:age_adult, "I'm over 21") %>
  
<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>